alter session set "_ORACLE_SCRIPT"=true; 

-- Carefully: this will change ARCHIVELOG Mode, need admin permission
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;
ALTER SYSTEM SWITCH LOGFILE;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;

-- CREATE USER
CREATE USER remote IDENTIFIED BY 123456;
ALTER USER remote quota unlimited ON USERS;

-- CREATE ROLE AND ASSIGN TO REMOTE
alter session set "_ORACLE_SCRIPT"=true; 
GRANT EXECUTE ON sys.dbms_logmnr TO remote;
GRANT EXECUTE ON DBMS_LOGMNR_D TO remote;
GRANT SELECT ON v$logmnr_contents TO remote;
GRANT SELECT ON v$log TO remote;
GRANT SELECT ON v$logfile TO remote;
GRANT SELECT ON v$archived_log TO remote;
GRANT SELECT ON v$parameter TO remote;
GRANT SELECT ON v$database TO remote;
GRANT SELECT ON v$log_history TO remote;
GRANT SELECT ON V$ARCHIVE_DEST_STATUS TO remote;
GRANT SELECT ON V$LOGMNR_LOGS TO remote;
GRANT SELECT ON V$THREAD TO remote;
GRANT SELECT ANY DICTIONARY TO remote;
GRANT SELECT ON v_$statname TO remote;
GRANT SELECT ON v_$mystat TO remote;
GRANT SELECT ON v_$session TO remote;

GRANT RESOURCE TO remote;
GRANT CONNECT TO remote;
GRANT CREATE TABLE TO remote;
GRANT CREATE SESSION TO remote;
GRANT SELECT ANY TRANSACTION TO remote;

create table REMOTE."User" (
	ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),
	NAME VARCHAR2(100) NULL
);